"""Fix enum genre

Revision ID: 856c2b823d4b
Revises: 4adda871104c
Create Date: 2024-09-17 23:49:32.751405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856c2b823d4b'
down_revision: Union[str, None] = '4adda871104c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'genre',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('system design', 'algo', 'databases', 'code', 'any', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'genre',
               existing_type=sa.Enum('system design', 'algo', 'databases', 'code', 'any', native_enum=False),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
